apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: helloo
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloo
  template:
    metadata:
      labels:
        app: helloo 
    spec:
      containers:
        - name: helloo
          image: happygokul/newimage:latest
          imagePullPolicy: Always
