apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-sv
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: loadbalancer-po
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: happygokul/newimage:latest
          imagePullPolicy: Always
